image: drone/scipy:2.7-pip
script: 
    - pip install -e .[docs,tests]
    - py.test
    - python setup.py build_sphinx
    - python setup.py egg_info -b.dev sdist --formats gztar


notify:
    email:
        on_failure: blame

deploy:
    bash:
        when:
            branch: master
        script:
            - scp -o StrictHostKeyChecking=no -P 22 -r dist/* $SERVER/pypi/
            - rsync -a --delete-before build/sphinx/html/* $SERVER/docs/pplt
